[package]
name = "part1_bench_consts"
version = "0.1.0"
authors = ["Suchir Kavi <suchirkavi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
